"""Initial migration

Revision ID: 1d6046414df1
Revises: 
Create Date: 2025-11-03 23:01:11.343477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6046414df1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('quote_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quote_content', sa.Text(), nullable=False),
    sa.Column('event_input', sa.String(length=200), nullable=True),
    sa.Column('mood_input', sa.String(length=100), nullable=True),
    sa.Column('weather', sa.String(length=50), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('is_birthday', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_quote_history_created_at'))

    op.drop_table('quote_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    # ### end Alembic commands ###
